name: batch_pipeline

pipeline: configs/pipeline/akaze_pipeline.yaml

dataset:
  root: datasets
  pattern_source: source
  pattern_target: target
  include: []

output:
  root: ../../outputs/batch/current
  save_visuals: true
  summary_csv: true
