name: contour_pipeline

structure: configs/structure/contour.yaml

io:
  image1: datasets/test1/source.png
  image2: datasets/test1/target.png
  output_dir: outputs

visualization:
  draw_keypoints: false
  draw_matches: false
  draw_inliers_only: true
  max_matches_drawn: 100
  warp: true
  show_source_window: false
  show_target_window: false
  show_warped_window: false
  wait_key: 0
